/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiMintUniversalSol from "./MultiMintUniversal.sol";
export type { multiMintUniversalSol };
import type * as nftSol from "./NFT.sol";
export type { nftSol };
export type { MyERC721 } from "./MyERC721";
